# Generated by Django 5.1 on 2024-08-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
