# Generated by Django 5.1 on 2024-08-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_blog_body'),
        ('core', '0006_alter_blog_body'),
    ]

    operations = [
    ]
